[model]
# path -> type(primitive type only)
# primitive type default value
# * string = ""
# * int = 0
# * bool = false
# * float = 0.0
# compound type default value
# * object = (not exist)
# * array = (not exist)
"user/user_id" = "string"
"user/username" = "string"
"user/password" = "string"
"user/nickname" = "string"
"user/time_created" = "int"
"user/time_updated" = "int"
"user/is_login" = "bool"
"user/risk/rating_core" = "float"
"user/phone[]/country_code" = "string"
"user/phone[]/area_code" = "string"
"user/phone[]/phone_number" = "string"
"user/login/lastLoginTime[]" = "int"
"user/risk/matrix[]/sub_matrix[]" = "float"

"forum/forum_id" = "string"
"forum/forum_name" = "string"
"forum/forum_description" = "string"
"forum/parent_forum_id" = "string"
"forum/status" = "int"
"forum/time_created" = "int"
"forum/time_updated" = "int"

"post/post_id" = "string"
"post/parent_post_id" = "string"
"post/post_type" = "int"
"post/author_id" = "int"
"post/forum_id" = "string"
"post/title" = "string"
"post/content" = "string"
"post/status" = "int"
"post/time_created" = "int"
"post/time_updated" = "int"

"debugging/database/affected_row_count" = "int"
"debugging/http/parameter" = "string"

"database/user/user_id" = "string"
"database/user/password" = "string"
"database/forum/forum_id" = "string"
"database/forum/parent_forum_id" = "string"
"database/post/parent_post_id" = "string"
"database/post/post_type" = "int"

"database/common_parameter/limit_count" = "int"

"posts[]/post_id" = "string"
"posts[]/parent_post_id" = "string"
"posts[]/post_type" = "int"
"posts[]/author_id" = "int"
"posts[]/forum_id" = "string"
"posts[]/title" = "string"
"posts[]/content" = "string"
"posts[]/status" = "int"
"posts[]/time_created" = "int"
"posts[]/time_updated" = "int"
